language: python
python: 2.7
sudo: false

addons:
  apt:
    sources:
    - mongodb-3.0-precise
    - pypy

addons:
  apt:
    packages:
    - mongodb-org-server
    - pypy

env:
    - TOX_ENV=py27-twlatest
    - TOX_ENV=py27-twtrunk
    - TOX_ENV=py27-tw154
    - TOX_ENV=py27-tw153
    - TOX_ENV=py27-tw150
    - TOX_ENV=py27-tw140
    - TOX_ENV=py33-twtrunk
    - TOX_ENV=py34-twtrunk
    - TOX_ENV=pypy-twtrunk
    - TOX_ENV=pyflakes
    - TOX_ENV=manifest

matrix:
  fast_finish: true
  allow_failures:
    - env: TOX_ENV=pyflakes
    - env: TOX_ENV=pypy-twtrunk


before_install:
  - "mongod --version"
  - "pypy --version"

install:
  - pip install tox coveralls

before_script:
  - "until nc -z localhost 27017; do echo Waiting for MongoDB; sleep 1; done"

script:
  - tox -e $TOX_ENV

after_success:
    - coveralls

notifications:
    email: false
